### ISSUE TITLE
Worker response (error) - login requests failing

### ISSUE THREAD

**Issue by ghost** [1994rstefan/Spotify-Ping-Pong-API#3]
@1994rstefan as of the past day or so, I am unable to login with @TooTallNate's node-spotify library (https://github.com/TooTallNate/node-spotify-web).  I'm currently running my own instance of the Ping Pong service (the nodestuff one appears to be down) which has been working fine for over a month or so.

Any thoughts on how to debug this and identify the problem?

```
Fri, 12 Jun 2015 16:22:23 GMT - workerProcess(109 124 42 223 4 19 191 236 207 155 32 40 211 226 43 161 100 1 32 208, cb) (-)
Fri, 12 Jun 2015 16:22:23 GMT - Worker response (0)
Fri, 12 Jun 2015 16:22:23 GMT - 201 - Worker response (error) "109 124 42 223 4 19 191 236 207 155 32 40 211 226 43 161 100 1 32 208:" (0)
Fri, 12 Jun 2015 16:22:23 GMT - Worker closed (0)
Fri, 12 Jun 2015 16:22:23 GMT - New worker (0)
Fri, 12 Jun 2015 16:22:56 GMT - workerProcess(8 52 240 160 109 69 206 115 253 35 80 63 77 238 187 68 245 237 39 94, cb) (-)
Fri, 12 Jun 2015 16:22:56 GMT - Worker response (0)
Fri, 12 Jun 2015 16:22:56 GMT - 201 - Worker response (error) "8 52 240 160 109 69 206 115 253 35 80 63 77 238 187 68 245 237 39 94:" (0)
Fri, 12 Jun 2015 16:22:56 GMT - Worker closed (0)
Fri, 12 Jun 2015 16:22:56 GMT - New worker (0)
Fri, 12 Jun 2015 16:23:50 GMT - workerProcess(81 91 230 120 32 68 186 68 233 79 206 39 76 212 140 25 76 237 146 197, cb) (-)
Fri, 12 Jun 2015 16:23:50 GMT - Worker response (0)
Fri, 12 Jun 2015 16:23:50 GMT - 201 - Worker response (error) "81 91 230 120 32 68 186 68 233 79 206 39 76 212 140 25 76 237 146 197:" (0)
Fri, 12 Jun 2015 16:23:50 GMT - Worker closed (0)
Fri, 12 Jun 2015 16:23:50 GMT - New worker (0)
```

**Comment by ghost** [comment]
Actually, on further review, the issue seems to be with running the worker in Firefox using screen as follows

```
screen Xvfb :0 -screen 0 1024x768x24
// exit screen with pressing control+a and then d
DISPLAY=:0 screen firefox http://localhost:8080/worker.html
```

This has worked for some time, but as of today it's causing the above errors.  Running the worker on a separate machine in a normal browser seems to work fine.

**Comment by 1994rstefan** [comment]
Hello,

the Ping-Pong-Service is now available again.

With the other Problem i can not help you, sorry. It's working fine for me without any Problems.
You could try to run a VNC-Server to see if firefox is outputing something.
Install x11vnc and run the following command:
`x11vnc -display :0`
You should now be able to connect via VNC.

**Comment by ghost** [comment]
Thanks for the help
